# =============
# Mybatis 配置
# =============
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

# =============
# Rocket 配置
# =============
rocketmq:
  producer:
    producer-group: tx-msg
    name-service-addr: 118.190.42.136:9876
    instance-name: testProducer

spring:
  # =======================
  # Spring-Datasource 配置
  # =======================
  datasource:
    url: jdbc:mysql://118.190.42.136:3306/message?allowMultiQueries=true
    username: msg
    password: msg
    driver-class-name: com.mysql.cj.jdbc.Driver
    # =======================
    # Druid-Pool 配置
    # =======================
    druid:
      initialSize: 5
      maxActive: 20
      minIdle: 5
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000;druid.stat.logSlowSql=true
      useGlobalDataSourceStat: true

  # ====================
  # Spring-JMX 配置
  # ====================
  jmx:
    enabled: false

# ===========
# LTS 配置
# ===========
lts:
  jobclient:
    cluster-name: test_cluster
    registry-address: zookeeper://118.190.42.136:2181
    node-group: message_jobClient
    use-retry-client: true
    configs:
      job.fail.store: mapdb
  tasktracker:
    cluster-name: test_cluster
    registry-address: zookeeper://118.190.42.136:2181
    node-group: message_TaskTracker
    configs:
      job.fail.store: mapdb
    dispatch-runner:
      enable: true
      shardValue: taskId
    work-threads: 64

# ===========
# Dubbo 配置
# ===========
dubbo:
  application:
    name: message-core-service
    logger: slf4j
  registry:
    address: zookeeper://118.190.42.136:2181
  protocol:
    name: dubbo
    port: 20902
    threads: 200
    payload: 88388608
  service-config:
    version: 1.0.0
    group: dev
    timeout: 10000
    retries: 0
  reference-config:
    version: 1.0.0
    group: dev
    timeout: 10000
    retries: 0
    check: false

# =========================
# Web容器(默认为tomcat) 配置
# =========================
server:
  port: 9092
  tomcat:
    uri-encoding: UTF-8